# Generated by Django 3.2.7 on 2021-09-18 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
