version: '3.7'

services: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on: 
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-thbtz_f370_2)+v0*aacf8hrn3rx&(43)o%x(unxyscbt!!n2-
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_docker
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
    ports: 
      - 3306:3306
      